In [47]:
# анализируем несколько .mol файлов
import numpy as np
import pandas as pd


def conn_type(comm):
    num_of_double = 0
    num_of_triple = 0
    for line in comm:
        if line[2] == '2':
            num_of_double += 1
        elif line[2] == '3':
            num_of_triple += 1
    if num_of_double == 0 and num_of_triple == 0:
        return 's'
    elif num_of_double == 1 and num_of_triple == 0:
        return 'd'
    elif num_of_double >= 2 and num_of_triple == 0:
        return 'w'
    elif num_of_triple > 0:
        return 't'
    else:
        print('WHAT')
        return '?'
    
def analize_mol_file1(molekula, file):# 1-цепочки
    with open(file) as f:
        lines = f.readlines()
        num_of_atoms = int(list(lines[3].split())[0])
        num_of_edges = int(list(lines[3].split())[1])
        end = lines.index('M  END\n')
        beg = 4 + num_of_atoms
        for elem in range(1, num_of_atoms+1):
            NN = lines[3+elem].split()[3] 
            num_of_neighbours = 0
            communic = [] #массив связей с конкретным элементом

            for i in range(end-beg):
                if int(list(lines[beg+i].split())[0]) == elem:
                    num_of_neighbours += 1
                    communic.append(list(lines[beg+i].split())[0:3])
                if int(list(lines[beg+i].split())[1]) == elem:
                    num_of_neighbours += 1
                    communic.append(list(lines[beg+i].split())[0:3])

            num_of_neighbours = str(num_of_neighbours)
            type_of_connection = conn_type(communic)
            name = NN + num_of_neighbours + type_of_connection

            if file in molekula.index:
                if name in molekula.columns:
                    if np.isnan(molekula[name][file]):
                        molekula.loc[file, name] = 1
                    else:
                        molekula.loc[file, name] += 1
                else:
                    molekula.loc[file, name] = 1
            else:
                molekula.loc[file, name] = 1
        

def analize_mol_file2(molekula, file):# 2-цепочки
    with open(file) as f:
        lines = f.readlines()
        num_of_atoms = int(list(lines[3].split())[0])
        num_of_edges = int(list(lines[3].split())[1])
        end = lines.index('M  END\n')
        beg = 4 + num_of_atoms
        for elem in range(1, num_of_atoms+1):
            connect = [] #массив связей с большим по номеру элементом

            for i in range(end-beg):
                if int(list(lines[beg+i].split())[0]) == elem and list(lines[beg+i].split())[1] > str(elem):
                    connect.append(list(lines[beg+i].split())[0:3])
                if int(list(lines[beg+i].split())[1]) == elem and list(lines[beg+i].split())[0] > str(elem):
                    connect.append(list(lines[beg+i].split())[0:3])
            for num in range(len(connect)):
                if int(connect[num][0]) == elem:
                    elem2 = int(connect[num][1])
                else:
                    elem2 = int(connect[num][0])
                NN1 = lines[3+elem].split()[3]
                NN2 = lines[3+elem2].split()[3]
                num_of_neighbours1 = 0
                num_of_neighbours2 = 0
                communic1 = []
                communic2 = []
                for i in range(end-beg):
                    if int(list(lines[beg+i].split())[0]) == elem:
                        num_of_neighbours1 += 1
                        communic1.append(list(lines[beg+i].split())[0:3])
                    if int(list(lines[beg+i].split())[1]) == elem:
                        num_of_neighbours1 += 1
                        communic1.append(list(lines[beg+i].split())[0:3])
                    if int(list(lines[beg+i].split())[0]) == elem2:
                        num_of_neighbours2 += 1
                        communic2.append(list(lines[beg+i].split())[0:3])
                    if int(list(lines[beg+i].split())[1]) == elem2:
                        num_of_neighbours2 += 1
                        communic2.append(list(lines[beg+i].split())[0:3])
                num_of_neighbours1 = str(num_of_neighbours1)
                type_of_connection1 = conn_type(communic1)
                num_of_neighbours2 = str(num_of_neighbours2)
                type_of_connection2 = conn_type(communic2)
                name1 = NN1 + num_of_neighbours1 + type_of_connection1
                name2 = NN2 + num_of_neighbours2 + type_of_connection2
                if name1 < name2:
                    name = name1 + name2
                else:
                    name = name2 + name1

                if file in molekula.index:
                    if name in molekula.columns:
                        if np.isnan(molekula[name][file]):
                            molekula.loc[file, name] = 1
                        else:
                            molekula.loc[file, name] += 1
                    else:
                        molekula.loc[file, name] = 1
                else:
                    molekula.loc[file, name] = 1
                

molekula = pd.DataFrame({})
# files = ["adrenalin.mol", "soil-1.mol"]
files = ["adrenalin.mol", "amaron.mol", "iervin.mol", 'acetona_peroxid.mol', 'aleiritic_acid.mol', "soil-1.mol"]
for file in files:
    analize_mol_file1(molekula, file)
molekula = molekula.fillna(0)
for file in files:
    analize_mol_file2(molekula, file)
molekula = molekula.fillna(0)
molekula

C2d  C3d  C3s   C2s  N2s  C1s  O1s  N2d  C4s  O2s  ...  \
adrenalin.mol         3.0  3.0  1.0   1.0  1.0  1.0  3.0  0.0  0.0  0.0  ...   
amaron.mol           20.0  8.0  0.0   0.0  0.0  0.0  0.0  2.0  0.0  0.0  ...   
iervin.mol            1.0  4.0  8.0   8.0  1.0  4.0  1.0  0.0  2.0  1.0  ...   
acetona_peroxid.mol   0.0  0.0  0.0   0.0  0.0  4.0  0.0  0.0  2.0  4.0  ...   
aleiritic_acid.mol    0.0  1.0  2.0  13.0  0.0  0.0  4.0  0.0  0.0  0.0  ...   
soil-1.mol            4.0  3.0  0.0   0.0  1.0  2.0  0.0  0.0  0.0  1.0  ...   

                     C4sO2s  C1sC3d  C3sO2s  C1sC3s  C3sN2s  O2sO2s  C2sO1s  \
adrenalin.mol           0.0     0.0     0.0     0.0     0.0     0.0     0.0   
amaron.mol              0.0     0.0     0.0     0.0     0.0     0.0     0.0   
iervin.mol              1.0     1.0     1.0     2.0     1.0     0.0     0.0   
acetona_peroxid.mol     4.0     0.0     0.0     0.0     0.0     2.0     0.0   
aleiritic_acid.mol      0.0     0.0     0.0     0.0     0.0     0.0     1.0   
soil-1.mol              0.0     1.0     0.0     0.0     0.0     0.0     0.0   

                     C3dN2s  C3dO2s  C1sO2s  
adrenalin.mol           0.0     0.0     0.0  
amaron.mol              0.0     0.0     0.0  
iervin.mol              0.0     0.0     0.0  
acetona_peroxid.mol     0.0     0.0     0.0  
aleiritic_acid.mol      0.0     0.0     0.0  
soil-1.mol              2.0     1.0     1.0  

[6 rows x 40 columns]

In [134]:
#анализируем .sdf файл

import numpy as np
import pandas as pd


def conn_type_big(comm, atom):
    num_of_double = 0
    num_of_triple = 0
    for row in comm:
        if row[0] == atom or row[1] == atom:
            if row[2] == 2:
                num_of_double += 1
            elif row[2] == 3:
                num_of_triple += 1
    if num_of_double == 0 and num_of_triple == 0:
        return 's'
    elif num_of_double == 1 and num_of_triple == 0:
        return 'd'
    elif num_of_double >= 2 and num_of_triple == 0:
        return 'w'
    elif num_of_triple > 0:
        return 't'
    else:
        print('WHAT')
        return '?'


def analize_sdf_file(mols, file, key):
    with open(file) as f:
        lines = f.readlines()
        begin = []
        end = []
        for i, line in enumerate(lines):
            if line == key:
                begin.append(i)
            if line == 'M  END\n':
                end.append(i)
        for molecula in range(len(begin)):
            num_of_atoms = int(list(lines[begin[molecula]+2].split())[0])
            num_of_edges = int(list(lines[begin[molecula]+2].split())[1])
            beg = num_of_atoms + begin[molecula] + 3
            connect = []
            nums_to_names = dict()
            nums_to_names2 = dict()
            nums_to_names3 = dict()
            for i in range(end[molecula]-beg):
                connect.append(list(map(int, list(lines[beg+i].split())[0:3])))
            # 1-цепочки
            for atom in range(1, num_of_atoms+1):
                NN = lines[begin[molecula]+2+atom].split()[3] 
                num_of_neighbors = 0
                for row in connect:
                    if atom == row[0] or atom == row[1]:
                        num_of_neighbors += 1
                num_of_neighbors = str(num_of_neighbors)
                type_of_connection = conn_type_big(connect, atom)
                name = NN + num_of_neighbors + type_of_connection
                nums_to_names[atom] = name                
                if molecula in mols.index:
                    if name in mols.columns:
                        if np.isnan(mols[name][molecula]):
                            mols.loc[molecula, name] = 1
                        else:
                            mols.loc[molecula, name] += 1
                    else:
                        mols.loc[molecula, name] = 1
                else:
                    mols.loc[molecula, name] = 1
            # 2-цепочки
            for atom in range(1, num_of_atoms+1):
                for row in connect:
                    if (row[0] == atom and row[1] > atom) or (row[1] == atom and row[0] > atom):
                        NNmas = sorted([nums_to_names[row[0]], nums_to_names[row[1]]])
                        NN = NNmas[0] + NNmas[1]
                        name = NN
#                         if row[2] == 1:
#                             name = NN + '_s'
#                         elif row[2] == 2:
#                             name = NN + '_d'
#                         elif row[2] == 3:
#                             name == NN + '_t'
#                         else:
#                             name == NN + '_?'
                        nums_to_names2[tuple(sorted((row[0], row[1])))] = name
                        if molecula in mols.index:
                            if name in mols.columns:
                                if np.isnan(mols[name][molecula]):
                                    mols.loc[molecula, name] = 1
                                else:
                                    mols.loc[molecula, name] += 1
                            else:
                                mols.loc[molecula, name] = 1
                        else:
                            mols.loc[molecula, name] = 1
            # 3-цепочки
            for pair in nums_to_names2.keys():
                for row in connect:
                    if (row[0] == pair[0] and row[1] > pair[1]) or (row[0] == pair[1] and row[1] > pair[0]):
                        if nums_to_names3.get(tuple(sorted([pair[0], pair[1], row[1]])), -1) == -1:                          
                            NNmas = sorted([nums_to_names2[pair], nums_to_names[row[1]]])
                            name = NNmas[0] + NNmas[1]
                            nums_to_names3[tuple(sorted([pair[0], pair[1], row[1]]))] = name
                    if (row[1] == pair[0] and row[0] > pair[1]) or (row[1] == pair[1] and row[0] > pair[0]):
                        if nums_to_names3.get(tuple(sorted([pair[0], pair[1], row[0]])), -1) == -1:                          
                            NNmas = sorted([nums_to_names2[pair], nums_to_names[row[0]]])
                            name = NNmas[0] + NNmas[1]
                            nums_to_names3[tuple(sorted([pair[0], pair[1], row[0]]))] = name
                    if molecula in mols.index:
                        if name in mols.columns:
                            if np.isnan(mols[name][molecula]):
                                mols.loc[molecula, name] = 1
                            else:
                                mols.loc[molecula, name] += 1
                        else:
                            mols.loc[molecula, name] = 1
                    else:
                        mols.loc[molecula, name] = 1
                        
                
        

In [135]:
mols = pd.DataFrame({})
file = 'soil-1-1.sdf'
key = '   - NASAWIN -\n'
analize_sdf_file(mols, file, key)
mols.shape

(328, 474)

In [136]:
mols.columns

Index(['C2d', 'C3d', 'N2s', 'C1s', 'O1d', 'O2s', 'C2dC2d', 'C2dC3d', 'C3dO2s',
       'C3dN2s',
       ...
       'C2sN3sN2d', 'N2dN2dN2s', 'N3dN3s', 'C1sN3d', 'C3dN3sN3d', 'C3dN3dN3s',
       'C1sN3dN3s', 'C1sC3dN3d', 'C3dN3dO2s', 'C3dN3dC4s'],
      dtype='object', length=474)

In [138]:
mols = mols.fillna(0)
mols

C2d  C3d  N2s  C1s  O1d  O2s  C2dC2d  C2dC3d  C3dO2s  C3dN2s  ...  \
0    4.0  3.0  1.0  2.0  1.0  1.0     2.0     4.0     1.0     2.0  ...   
1    5.0  2.0  1.0  1.0  1.0  0.0     4.0     2.0     0.0     2.0  ...   
2    4.0  3.0  1.0  1.0  1.0  0.0     2.0     4.0     0.0     2.0  ...   
3    4.0  3.0  1.0  1.0  3.0  0.0     2.0     4.0     0.0     2.0  ...   
4    4.0  3.0  1.0  1.0  1.0  0.0     2.0     4.0     0.0     2.0  ...   
..   ...  ...  ...  ...  ...  ...     ...     ...     ...     ...  ...   
323  3.0  3.0  1.0  1.0  0.0  0.0     1.0     4.0     0.0     1.0  ...   
324  3.0  3.0  1.0  0.0  0.0  0.0     1.0     4.0     0.0     1.0  ...   
325  3.0  3.0  1.0  0.0  0.0  0.0     1.0     4.0     0.0     1.0  ...   
326  3.0  3.0  1.0  1.0  0.0  1.0     1.0     4.0     1.0     1.0  ...   
327  2.0  6.0  0.0  6.0  1.0  2.0     0.0     4.0     3.0     0.0  ...   

     C2sN3sN2d  N2dN2dN2s  N3dN3s  C1sN3d  C3dN3sN3d  C3dN3dN3s  C1sN3dN3s  \
0          0.0        0.0     0.0     0.0        0.0        0.0        0.0   
1          0.0        0.0     0.0     0.0        0.0        0.0        0.0   
2          0.0        0.0     0.0     0.0        0.0        0.0        0.0   
3          0.0        0.0     0.0     0.0        0.0        0.0        0.0   
4          0.0        0.0     0.0     0.0        0.0        0.0        0.0   
..         ...        ...     ...     ...        ...        ...        ...   
323        0.0       30.0     0.0     0.0        0.0        0.0        0.0   
324        0.0       12.0     0.0     0.0        0.0        0.0        0.0   
325        0.0       12.0     0.0     0.0        0.0        0.0        0.0   
326        0.0       26.0     0.0     0.0        0.0        0.0        0.0   
327        0.0        0.0     1.0     1.0        1.0       28.0        1.0   

     C1sC3dN3d  C3dN3dO2s  C3dN3dC4s  
0          0.0        0.0        0.0  
1          0.0        0.0        0.0  
2          0.0        0.0        0.0  
3          0.0        0.0        0.0  
4          0.0        0.0        0.0  
..         ...        ...        ...  
323        0.0        0.0        0.0  
324        0.0        0.0        0.0  
325        0.0        0.0        0.0  
326        0.0        0.0        0.0  
327        2.0        1.0       24.0  

[328 rows x 474 columns]

In [152]:
def distanceMatrix(Matr):
    """Получает матрицу смежности Matr
        и возвращает матрицу расстояний
        в рёбрах"""
    ln = Matr.shape[0]
    res = np.zeros((ln, ln))
    
    for i in range(ln):#Запускаем цикл по всем вершинам
        #BFS в каждой вершине
        que = []#Очередь вершин
        dist = []#Очередь расстояний
        que.append(i)
        dist.append(0)
        while len(que) != 0:
            for j in range(ln):#Бежим по строке матрицы смежности
                if Matr[i, j] != 0 and res[i, j] != 0:#Если есть ребро + не записывали ещё в матрицу
                    que.append(j)
                    dist.append(dist[0] + 1)
            if res[i, j] != 0:
                res[i,j] = dist[0]
            del que[0]
            del dist[0]

In [156]:
with open(file) as f:
    lines = f.readlines()
    begin = []
    end = []
    for i, line in enumerate(lines):
        if line == key:
            begin.append(i)
        if line == 'M  END\n':
            end.append(i)
    num_of_atoms = int(list(lines[begin[0]+2].split())[0])
    beg = num_of_atoms + begin[0] + 3
    matrix = np.zeros(num_of_atoms*num_of_atoms).reshape(num_of_atoms, num_of_atoms)
    connect = []
    for i in range(end[0]-beg):
        connect.append(list(map(int, list(lines[beg+i].split())[0:3])))
    for row in connect:
        matrix[row[0]-1][row[1]-1] = 1
        matrix[row[1]-1][row[0]-1] = 1
    for i in range(num_of_atoms):
        matrix[i][i] = 1
print(matrix)
distanceMatrix(matrix)

[[1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]]
